In [ ]:
#Numpy array
#creating numpy array

import numpy as np

arr=np.array([1,2,3,4,5,6])
print(arr)


[1 2 3 4 5 6]


In [ ]:
#creating array with all zeros

arr=np.zeros((3,3)) #3 by 3 matrix
print(arr)


print("\n")
print("--------------")

arr=np.zeros((2,2))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


--------------
[[0. 0.]
 [0. 0.]]


In [ ]:
# creating array with all ones

arr = np.ones((3, 2)) # 3 rows, 2 columns
print(arr)

print("\n")
print("--------------")

arr = np.ones((4, 4))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


--------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# creating array with a range of values

arr = np.arange(10) # 0 to 9
print(arr)

print("\n")
print("--------------")

arr = np.arange(2, 10, 2) # start at 2, end before 10, step of 2
print(arr)

[0 1 2 3 4 5 6 7 8 9]


--------------
[2 4 6 8]


In [ ]:
# Reshaping arrays

arr = np.arange(12)
print("Original array:", arr)

reshaped_arr = arr.reshape(3, 4) # reshape to a 3x4 matrix
print("Reshaped array:\n", reshaped_arr)

print("\n")
print("--------------")

reshaped_arr = arr.reshape(2, 6) # reshape to a 2x6 matrix
print("Reshaped array:\n", reshaped_arr)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


--------------
Reshaped array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


# Task
Write all basic operations for arrays, including arithmetic, comparison, aggregate, slicing, indexing, and broadcasting.

## Array arithmetic operations

### Subtask:
Demonstrate element-wise addition, subtraction, multiplication, and division on arrays.


**Reasoning**:
Create two NumPy arrays and perform element-wise arithmetic operations as requested in the instructions.



In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

# Element-wise addition
addition_result = arr1 + arr2
print("\nElement-wise addition:\n", addition_result)

# Element-wise subtraction
subtraction_result = arr1 - arr2
print("\nElement-wise subtraction:\n", subtraction_result)

# Element-wise multiplication
multiplication_result = arr1 * arr2
print("\nElement-wise multiplication:\n", multiplication_result)

# Element-wise division
# To avoid division by zero, ensure arr2 does not contain zeros if arr1 has non-zero values
# In this example, arr2 has no zeros, so direct division is safe.
division_result = arr1 / arr2
print("\nElement-wise division:\n", division_result)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Element-wise addition:
 [[ 6  8]
 [10 12]]

Element-wise subtraction:
 [[-4 -4]
 [-4 -4]]

Element-wise multiplication:
 [[ 5 12]
 [21 32]]

Element-wise division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


## Array comparison operations

### Subtask:
Show how to compare arrays element-wise.


**Reasoning**:
Create two NumPy arrays and perform element-wise comparison operations between them.



In [ ]:
arr1 = np.array([[1, 5], [3, 8]])
arr2 = np.array([[2, 5], [4, 7]])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

# Element-wise comparisons
equal_comparison = arr1 == arr2
print("\nElement-wise == comparison:\n", equal_comparison)

not_equal_comparison = arr1 != arr2
print("\nElement-wise != comparison:\n", not_equal_comparison)

greater_than_comparison = arr1 > arr2
print("\nElement-wise > comparison:\n", greater_than_comparison)

less_than_comparison = arr1 < arr2
print("\nElement-wise < comparison:\n", less_than_comparison)

greater_equal_comparison = arr1 >= arr2
print("\nElement-wise >= comparison:\n", greater_equal_comparison)

less_equal_comparison = arr1 <= arr2
print("\nElement-wise <= comparison:\n", less_equal_comparison)

Array 1:
 [[1 5]
 [3 8]]
Array 2:
 [[2 5]
 [4 7]]

Element-wise == comparison:
 [[False  True]
 [False False]]

Element-wise != comparison:
 [[ True False]
 [ True  True]]

Element-wise > comparison:
 [[False False]
 [False  True]]

Element-wise < comparison:
 [[ True False]
 [ True False]]

Element-wise >= comparison:
 [[False  True]
 [False  True]]

Element-wise <= comparison:
 [[ True  True]
 [ True False]]


## Array aggregate operations

### Subtask:
Explain how to use functions like sum, mean, min, max, etc., on arrays.


**Reasoning**:
Create a NumPy array and demonstrate aggregate functions like sum, mean, min, and max, including their use with the axis parameter.



In [ ]:
# Create a new NumPy array for aggregate operations
arr_agg = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Array for aggregation:\n", arr_agg)

# Calculate and print the sum of all elements
total_sum = arr_agg.sum()
print("\nSum of all elements:", total_sum)

# Calculate and print the mean of all elements
overall_mean = arr_agg.mean()
print("Mean of all elements:", overall_mean)

# Find and print the minimum value
minimum_value = arr_agg.min()
print("Minimum value:", minimum_value)

# Find and print the maximum value
maximum_value = arr_agg.max()
print("Maximum value:", maximum_value)

# Demonstrate aggregates along specific axes (for 2D array)
# Sum along axis 0 (columns)
sum_along_axis0 = arr_agg.sum(axis=0)
print("\nSum along axis 0:", sum_along_axis0)

# Sum along axis 1 (rows)
sum_along_axis1 = arr_agg.sum(axis=1)
print("Sum along axis 1:", sum_along_axis1)

# Mean along axis 0 (columns)
mean_along_axis0 = arr_agg.mean(axis=0)
print("Mean along axis 0:", mean_along_axis0)

# Mean along axis 1 (rows)
mean_along_axis1 = arr_agg.mean(axis=1)
print("Mean along axis 1:", mean_along_axis1)

Array for aggregation:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Sum of all elements: 450
Mean of all elements: 50.0
Minimum value: 10
Maximum value: 90

Sum along axis 0: [120 150 180]
Sum along axis 1: [ 60 150 240]
Mean along axis 0: [40. 50. 60.]
Mean along axis 1: [20. 50. 80.]


## Array slicing and indexing

### Subtask:
Illustrate how to access specific elements or subarrays.


**Reasoning**:
Create a NumPy array and demonstrate different ways to access elements and subarrays using integer indexing, slicing, boolean indexing, and fancy indexing.



In [ ]:
# 1. Create a NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Original array:\n", arr)

# 2. Demonstrate accessing a single element using integer indexing
print("\nAccessing element at row 1, column 2 (0-indexed):", arr[1, 2])

# 3. Demonstrate slicing a portion of the array
# Slicing a 1D array (create a new 1D array first for clarity)
arr_1d = np.arange(10)
print("\nOriginal 1D array:", arr_1d)
print("Slicing a portion (elements from index 3 up to, but not including, index 7):", arr_1d[3:7])

# Slicing a subgrid in a 2D array (rows 0 and 1, columns 1 and 2)
print("\nSlicing a subgrid (rows 0 to 1, columns 1 to 2):\n", arr[0:2, 1:3])

# 4. Demonstrate using boolean indexing
# Select elements greater than 5
print("\nElements greater than 5 using boolean indexing:", arr[arr > 5])

# 5. Demonstrate using fancy indexing
# Select specific rows (row 0 and row 2)
print("\nSelecting specific rows (row 0 and row 2) using fancy indexing:\n", arr[[0, 2]])

# Select specific elements (element at (0,0), (1,1), and (2,0))
print("\nSelecting specific elements using fancy indexing:", arr[[0, 1, 2], [0, 1, 0]])

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Accessing element at row 1, column 2 (0-indexed): 6

Original 1D array: [0 1 2 3 4 5 6 7 8 9]
Slicing a portion (elements from index 3 up to, but not including, index 7): [3 4 5 6]

Slicing a subgrid (rows 0 to 1, columns 1 to 2):
 [[2 3]
 [5 6]]

Elements greater than 5 using boolean indexing: [6 7 8 9]

Selecting specific rows (row 0 and row 2) using fancy indexing:
 [[1 2 3]
 [7 8 9]]

Selecting specific elements using fancy indexing: [1 5 7]


## Broadcasting

### Subtask:
Briefly explain and show examples of broadcasting with arrays.


**Reasoning**:
Provide a markdown explanation of NumPy broadcasting.



 ### Broadcasting

NumPy's broadcasting is a powerful mechanism that allows arithmetic operations between arrays with different shapes. Under certain constraints, the smaller array is "broadcast" across the larger array so that they have compatible shapes for the operation. This avoids the need to explicitly create larger copies of the smaller array, leading to more efficient code.

The broadcasting rule follows a few steps:
1. If the arrays have different numbers of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
2. If the shapes of the two arrays do not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised. """


**Reasoning**:
The previous command failed because the markdown content was not correctly formatted within a code block. I will now create a markdown cell to explain broadcasting and then proceed with creating arrays and demonstrating broadcasting with a scalar and an array, as well as with two compatible arrays.



In [ ]:
# Create a NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Original array:\n", arr)

# Create a scalar value
scalar = 10
print("\nScalar value:", scalar)

# Demonstrate broadcasting with an array and a scalar (addition)
broadcast_scalar_result = arr + scalar
print("\nResult of array + scalar broadcasting:\n", broadcast_scalar_result)

print("\n" + "-"*20)

# Create two NumPy arrays with compatible shapes for broadcasting
arr_compatible1 = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]]) # Shape (3, 3)
arr_compatible2 = np.array([10, 20, 30]) # Shape (3,) - will be broadcast to (1, 3) and then (3, 3)
print("Array 1 (shape {}):\n{}".format(arr_compatible1.shape, arr_compatible1))
print("Array 2 (shape {}):\n{}".format(arr_compatible2.shape, arr_compatible2))

# Demonstrate broadcasting with two compatible arrays (addition)
broadcast_compatible_result = arr_compatible1 + arr_compatible2
print("\nResult of compatible array broadcasting:\n", broadcast_compatible_result)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Scalar value: 10

Result of array + scalar broadcasting:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

--------------------
Array 1 (shape (3, 3)):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2 (shape (3,)):
[10 20 30]

Result of compatible array broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


**Reasoning**:
The previous code block successfully demonstrated broadcasting with a scalar and with compatible arrays. Now, I will create two arrays with incompatible shapes and attempt an arithmetic operation to show the broadcasting error, and then finish the subtask.



In [ ]:
# Create two NumPy arrays with incompatible shapes for broadcasting
arr_incompatible1 = np.array([[1, 2, 3],
                              [4, 5, 6]]) # Shape (2, 3)
arr_incompatible2 = np.array([10, 20])    # Shape (2,)

print("Array 1 (shape {}):\n{}".format(arr_incompatible1.shape, arr_incompatible1))
print("Array 2 (shape {}):\n{}".format(arr_incompatible2.shape, arr_incompatible2))

# Attempt an arithmetic operation (addition) to show the broadcasting error
# This will raise a ValueError because the shapes (2, 3) and (2,) are not compatible for broadcasting
try:
    broadcast_incompatible_result = arr_incompatible1 + arr_incompatible2
    print("\nResult of incompatible array broadcasting:\n", broadcast_incompatible_result)
except ValueError as e:
    print("\nError attempting broadcasting with incompatible shapes:")
    print(e)

# Add a comment explaining why it fails
# The shapes (2, 3) and (2,) are incompatible for broadcasting because
# when comparing the shapes from the trailing dimension forward:
# The last dimensions (3 and 2) do not match and neither is 1.
# The second to last dimensions (2 and 1 - after padding arr_incompatible2's shape to (1, 2) then stretching)
# would be compared as 2 and 1 (after padding and stretching arr_incompatible2 to (2,2)),
# leading to a mismatch in the last dimension (3 vs 2).


Array 1 (shape (2, 3)):
[[1 2 3]
 [4 5 6]]
Array 2 (shape (2,)):
[10 20]

Error attempting broadcasting with incompatible shapes:
operands could not be broadcast together with shapes (2,3) (2,) 


## Summary:

### Data Analysis Key Findings

*   NumPy supports element-wise arithmetic operations ($+$, $-$, $*$, $/$), comparison operations ($==$, $!=$, $>$, $<$, $>=$, $<=$,) and aggregate functions (sum, mean, min, max) on arrays.
*   Aggregate functions can be applied to the entire array or along specific axes.
*   Individual elements and subarrays can be accessed using integer indexing, slicing, boolean indexing, and fancy indexing.
*   Broadcasting allows operations between arrays of different shapes under specific compatibility rules, extending the smaller array to match the shape of the larger one.
*   Attempting broadcasting with incompatible shapes results in a `ValueError`.

### Insights or Next Steps

*   Understanding broadcasting is crucial for efficient array operations in NumPy, especially when dealing with arrays of different dimensions or shapes.
*   Explore more advanced indexing and slicing techniques, such as using `np.newaxis` or combining different indexing methods.
