In [3]:
import numpy as np


In [88]:
# Array with int data type and row=3 , col=4

arr2d= np.zeros(shape=(3,4), dtype=int)


print(arr2d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [89]:
#array with flot data type

arr2d=np.zeros(shape=(3,4), dtype=float)
print(arr2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [90]:
#array with string data type

arr2d= np.zeros(shape=(3,4), dtype= str)

print(arr2d)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [91]:
arr2d=np.array([[1,2,3,4,5],[6,7,8,8,4]])
print(arr2d)
print(arr2d.dtype)


[[1 2 3 4 5]
 [6 7 8 8 4]]
int64


In [92]:
arr2d=np.array([[1.1, 2, 3 ],[1.2,3,4]])
print(arr2d)

print(arr2d.dtype)

[[1.1 2.  3. ]
 [1.2 3.  4. ]]
float64


# Printing the row and col using index number of given matrix

In [93]:
a=np.array([[1,2,3,4],[11,22,33,44],[12,13,14,15]])
print(a)

[[ 1  2  3  4]
 [11 22 33 44]
 [12 13 14 15]]


In [94]:
#printing the row using index number
print("printing the first row : ",a[0])

printing the first row :  [1 2 3 4]


In [95]:
#Printing the 3rd row using index number
print("printing the 3rd row ",a[2])

printing the 3rd row  [12 13 14 15]


In [96]:
# printing any specefic value from the row of given matrix
print("the value of first value in row 1 : a[0][0] ")
print(a[0][0])


the value of first value in row 1 : a[0][0] 
1


In [97]:
#printing the 3rd row and 3rd index value

print("third row : ", a[2])
print("the 3rd value of row 3rd row :" , a[2][2])

third row :  [12 13 14 15]
the 3rd value of row 3rd row : 14


# Accessing the shape and the size of 2d Matrix

In [98]:
arr2d=np.zeros(shape=(3,4) ,dtype=int)

print(" the matrix : ")
print(arr2d)




 the matrix : 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [99]:
#counting the row and colum of the matrix
row,col= arr2d.shape
print("the number of the row : -> ",row)
print("the number of colum : -> ", col)

the number of the row : ->  3
the number of colum : ->  4


In [100]:
#counting the total cell of this matrix
total_cell = arr2d.size
print(" total cell of that matrix : ",total_cell)

 total cell of that matrix :  12


# Interaction of 2D matrix

In [101]:
arr= np.array([[1,2,3,4], [9,91,99,98]])

row_len, col_len= arr.shape
print(arr)
print("row : ",row_len)
print("col : ", col_len)


[[ 1  2  3  4]
 [ 9 91 99 98]]
row :  2
col :  4


In [102]:
for r in range(row_len):
  for c in range(col_len):
    print(arr[r][c],end=" ")
  print()

1 2 3 4 
9 91 99 98 


# Scalar and  Matrix multiplication  

In [103]:
A= np.array([[1,2,3,4], [11,22,33,44]])
print("the matrix : ")
print(A)

# Now we will multiply our matrix with 2
print()
print(" multliplying 2 with the matrix  : ")


row,col= A.shape
for r in range(row):
  for c in range(col):
    A[r][c]= 2 * A[r][c]
print( "after the matrix A ")
print()
print(A)

the matrix : 
[[ 1  2  3  4]
 [11 22 33 44]]

 multliplying 2 with the matrix  : 
after the matrix A 

[[ 2  4  6  8]
 [22 44 66 88]]


In [104]:
A=np.array( [[0,5],[1,2],[3,4]] )
B=np.array( [[3,2,1],[1,2,4]] )
print("A(3,2):")
print(A)
print("B(2,3):")
print(B)
Ar_len , Ac_len = A.shape[0], A.shape[1]
Br_len , Bc_len = B.shape[0], B.shape[1]
#Here, Bc_len==1 and Ac_len==Br_len
C=np.zeros( shape=(Ar_len,Bc_len), dtype=int)
Cr_len, Cc_len = C.shape[0], C.shape[1]
for i in range(Cr_len):
    for j in range(Cc_len):
        sum=0
        for k in range(Br_len):
           sum += A[i][k] * B[k][j]
        C[i][j] = sum
print("A X B = C(3,3):")
print(C)


A(3,2):
[[0 5]
 [1 2]
 [3 4]]
B(2,3):
[[3 2 1]
 [1 2 4]]
A X B = C(3,3):
[[ 5 10 20]
 [ 5  6  9]
 [13 14 19]]


In [4]:
a=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

# printing row wise

r,c= a.shape

for r in range(r):
  for j in range(c):
    print(a[r][j], end=" ")
  print()




1 2 3 4 
5 6 7 8 
9 10 11 12 
