In [14]:
import numpy as np

#Python 2D matrix using numpy


In [15]:
arr2d= [
    [1,2,3],
    [4,5,6]
]

print(arr2d)

[[1, 2, 3], [4, 5, 6]]


In [5]:
arr2d= np.zeros( shape = (3,3), dtype=int)

print(arr2d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
arr2d= np.zeros( shape=(3,3), dtype= float)

print(arr2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
arr2d= np.zeros (shape = (3,3) , dtype= str)


print(arr2d)

[['' '' '']
 ['' '' '']
 ['' '' '']]


#2d matrix using list in numpy

In [18]:
arr2d= ([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

print(arr2d)



[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [21]:
#Using numpy

arr2d= np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
    ])


print(arr2d)
print(f" DATA TYPE : { arr2d.dtype} ")

[[1 2 3]
 [1 2 3]
 [1 2 3]]
 DATA TYPE : int64 


In [23]:
arr2d= np.array([
    [1,2,3],
    [1.1,1.2,1.2],
    [1,2,3.3]

])

print(arr2d.dtype)

float64


#indexing in 2D matrix :

In [29]:
a=np.array([
    [1,   2,   3   ,4],
    [11,  22,  33, 44],
    [123,234,5667,344]
])


print(a)

print(f" =========================")
print(f" Printing the first row : {a[0]}")
print(f" =========================")
print(f" Printing the second row : {a[1]}")
print(f" =========================")
print(f" Printing the third row : {a[2]}")


[[   1    2    3    4]
 [  11   22   33   44]
 [ 123  234 5667  344]]
 Printing the first row : [1 2 3 4]
 Printing the second row : [11 22 33 44]
 Printing the third row : [ 123  234 5667  344]


In [45]:
print(f"Printing the third cell :{ a[0][2]}")

print(f"Printing the 4th cell :{ a[0][3]}")


print(f"Printing the third cell of 2nd row  :{ a[1][2]}")

print(f"total cell in that matrix : {a.size}")

Printing the third cell :3
Printing the 4th cell :4
Printing the third cell of 2nd row  :33
total cell in that matrix : 12


#Accessing the shape and the size of a 2d matrix :

In [42]:
arr2d= np.zeros( shape = (3,3), dtype = int)
print(" the matrix : \n")
print(arr2d)

row,col= arr2d.shape
print(f" \n The number of row of that matrix : {row }")

print(f"the number of col in that matrix :{ col}")

 the matrix : 

[[0 0 0]
 [0 0 0]
 [0 0 0]]
 
 The number of row of that matrix : 3
the number of col in that matrix :3


# #Iteration of 2D matrix :

In [52]:
a= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

r,c= a.shape

for i in range(r):
  for j in range(c):
    print(a[i][j], end= " ")
  print()

3
3
1 2 3 
4 5 6 
7 8 9 


In [54]:
a= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

r,c= a.shape


for i in range(c) :
  for j in range(r) :
    print(a[j][i]
    , end= " ")
  print()

1 4 7 
2 5 8 
3 6 9 


#Matrix scelar multiplication :

In [67]:
A= np.array([
    [1,2,3],
    [4,5,6]
])

print(f"the previous matrix :" )
print(A)

r,c= A.shape


for row in range( r) :
  for col in range( c ):
       A [row][col] = 2* A[row][col]
print("\n After multyplying with 2 : \n ")
print(A)

the previous matrix :
[[1 2 3]
 [4 5 6]]

 After multyplying with 2 : 
 
[[ 2  4  6]
 [ 8 10 12]]
